### PR TITLE
Fix timer picker ui bug when hours >= 10

### LINKED ISSUE #48: Timer picker expands when time is > 10 hours
Minor UI bug:
1. Click "+" next to Timer
2. Increment hours until time reaches "10:00"
3. Observe the buttons move/grow.

Expected behavior would be for buttons to not change in position or width.

https://user-images.githubusercontent.com/10577605/167972636-3fa6ffc5-5ebb-4aec-92f9-a90e7c5cb249.mp4

### PR DESCRIPTION
**Pull request by Peginaw**
This change resolves #48 by fixing the ui jitter when selected hour goes from 9 to 10
- Pad the hour number to have at least 2 digits
- Set the width of the "Set" and "Cancel" buttons to be 50% of the screen width, rather than equal to the width of the above components. Even if hours goes to 100 they'll stay at their fixed size

P.S. This is my first pull request on a real project that I actually use. Thanks for making the app!

### CODE REVIEW

File: app/src/main/java/dalbers/com/noise/playerscreen/view/TimerPicker.kt [hunk 1]
```diff
@@ -108,7 +113,7 @@ private fun TimeUnitPicker(
             Icon(Icons.Default.Add, contentDescription = "")
         }
         Text(
-            text = value.toString(),
+            text = String.format("%1$" + digitPositions + "s", value.toString()).replace(' ', '0'),
```
Comment (Peginaw) [inline app/src/main/java/dalbers/com/noise/playerscreen/view/TimerPicker.kt:116]: String.format() pads with spaces, so .replace is used to convert them to zeros.

**Comment by davidalbers** [comment]
Thank you so much for working on this issue! Looks good, and I'll try to get it into a release soon.
Sorry about the slow response!
